name: Run Unit Tests (with Coverage)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Test Coverage - Node.js ${{ matrix.node-version }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        node-version: [ 16.x, 18.x ]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }} environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run coverage check
        run: yarn coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
